spring:
  messages:
    basename: i18n.login
    encoding: UTF-8
  mvc:
    static-path-pattern: /**
#    view:
#      prefix: /
#      suffix: .html
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
# 允许IOC循环依赖引用
  main:
    allow-circular-references: true
  thymeleaf:
    cache: false
    mode: LEGACYHTML5


server:
  port: 8082
  servlet:
    context-path: /

logging:
  config: classpath:logback-spring.xml
  file:
    path: ./logs